// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD481E9kpTqXcDpIr-1d8ZfWVlAXWTWJ6k',
    appId: '1:542914496192:web:5bee2e32bdbae45d628f25',
    messagingSenderId: '542914496192',
    projectId: 'call-service-f7b4d',
    authDomain: 'call-service-f7b4d.firebaseapp.com',
    storageBucket: 'call-service-f7b4d.appspot.com',
    measurementId: 'G-16FZV6QLFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDTNBHnJugZbKJiQCA-EXH5nBtuumuFt0',
    appId: '1:542914496192:android:753cc8d5e3755cbf628f25',
    messagingSenderId: '542914496192',
    projectId: 'call-service-f7b4d',
    storageBucket: 'call-service-f7b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkVizUayCTHQZXt7HNDTXKkGEqzs7o9WA',
    appId: '1:542914496192:ios:02b19dd0c33a3edc628f25',
    messagingSenderId: '542914496192',
    projectId: 'call-service-f7b4d',
    storageBucket: 'call-service-f7b4d.appspot.com',
    iosBundleId: 'com.example.callService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkVizUayCTHQZXt7HNDTXKkGEqzs7o9WA',
    appId: '1:542914496192:ios:02b19dd0c33a3edc628f25',
    messagingSenderId: '542914496192',
    projectId: 'call-service-f7b4d',
    storageBucket: 'call-service-f7b4d.appspot.com',
    iosBundleId: 'com.example.callService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD481E9kpTqXcDpIr-1d8ZfWVlAXWTWJ6k',
    appId: '1:542914496192:web:5dd0ba2d0aec1e1d628f25',
    messagingSenderId: '542914496192',
    projectId: 'call-service-f7b4d',
    authDomain: 'call-service-f7b4d.firebaseapp.com',
    storageBucket: 'call-service-f7b4d.appspot.com',
    measurementId: 'G-6EW7VTCQBW',
  );

}